DSN: <username>:<password>@tcp(localhost:3306)/<database_name> # MySQL DSN
PORT: 8081 # API Port. Make sure this matches your nginx!

# Environment mode (development | production | maintenance)
MODE: dev