DSN: <username>:<password>@tcp(localhost:3306)/<database_name> # MySQL DSN
PORT: 8081 # API Port. Make sure this matches your nginx!

# Redis config, mini:<key_name>
REDIS_ADDR: localhost:6379
REDIS_PW:

# Environment mode (development | production)
MODE: development

# JWT Secret (you can generate one here: https://www.grc.com/passwords.htm)
SECRET: hello-world

# Relative directory for documentation
DOCS: ../docs

# Profile photo options
PFP_PATH: /home/username/example/bancho.py/.data/avatars # path to server's avatars
PFP_MAX: 1000000 # Profile photo size limit in bytes

# Cors options
CORS:
  - http://server-name.ca
  - https://server-name.ca

# For local testing
# CORS:
#   - http://192.168.0.19:8081 (whatever host:port the frontend is running on)
